<a href="https://colab.research.google.com/github/ckckck1373/LearnPytorch/blob/master/AUTOGRAD_Tutorials1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [36]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [37]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [38]:
print(y.grad_fn)

In [39]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [40]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)#input flag defaults to False if not given
a.requires_grad_(True) #.requires_grad changes an exitsting Tensor's requires_grad
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [41]:
#Gradients
out.backward() #equivalent to out.backward(torch.tensor(1.))
print(x.grad) #Print gradients d(out)/dx

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [44]:
#Next example of vector_Jacobian product:
x = torch.randn(3, requires_grad=True)
print(x)

y = x * 2
while y.data.norm() < 1000:
  y = y * 2
print(y)


tensor([-0.4540,  0.9689,  1.0584], requires_grad=True)
tensor([-464.8593,  992.1240, 1083.7760], grad_fn=<MulBackward0>)


In [45]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [47]:
print(x.requires_grad)
print((x ** 2).requires_grad)
with torch.no_grad():
  print((x ** 2).requires_grad)

True
True
False


You can also stop autograd from tracking history on Tensors with .requires_grad=True by wrapping the code block in with torch.no_grad():