<a href="https://colab.research.google.com/github/ckckck1373/LearnPytorch/blob/master/AUTOGRAD_Tutorials1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [82]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [83]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [84]:
print(y.grad_fn)

In [85]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [86]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)#input flag defaults to False if not given
a.requires_grad_(True) #.requires_grad changes an exitsting Tensor's requires_grad
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [87]:
#Gradients
out.backward() #equivalent to out.backward(torch.tensor(1.))
print(x.grad) #Print gradients d(out)/dx

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [88]:
#Next example of vector_Jacobian product:
x = torch.randn(3, requires_grad=True)
print(x)

y = x * 2
while y.data.norm() < 1000:#和torch.sqrt(torch.sum(torch.pow(y, 2)))相等
  y = y * 2
print(y)


tensor([-0.7250,  0.4945,  1.3900], requires_grad=True)
tensor([-742.3835,  506.3882, 1423.3116], grad_fn=<MulBackward0>)


In [89]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


Now in this case y is no longer a scalar. torch.autograd could not compute the full Jacobian directly, but if we just want the vector-Jacobian product, simply pass the vector to backward as argument:


The short answer is, you can’t compute a gradient unless it is with respect to a scalar quantity, because the gradient says how much the parameter would change if you vary the output: it makes sense that you can bump a scalar up and down, but if you have a matrix, how would you vary that? The tensor v specifies exactly in what sense you are “varying” the matrix, so that you can still compute a gradient. We don’t ever compute Jacobians, because in DL they are not usually needed.

In [90]:
print(x.requires_grad)
print((x ** 2).requires_grad)
with torch.no_grad():
  print((x ** 2).requires_grad)

True
True
False


You can also stop autograd from tracking history on Tensors with .requires_grad=True by wrapping the code block in with torch.no_grad():